#! /usr/bin/env node

"use strict";

let fs = require("fs"),
    pegjs = require("pegjs"),
    nomnom = require("nomnom"),
    beautify = require("js-beautify"),
    json = require("./package.json"),
    compiler = require("./src/compiler");

let opts = nomnom
.option("files", {
    position: 0,
    help: "Files to compile. The compiled versions will be saved with the same filename, except with a .js extension.",
    list: true
})
.option("stdout", {
    abbr: "s",
    flag: true,
    help: "instead of saving compiled source, output to stdout "
})
.option("debug", {
    abbr: "d",
    flag: true,
    help: "debug mode"
})
.option("version", {
    flag: true,
    help: "display the version number",
    callback: function () {
        return "version " + json.version;
    }
})
.parse();

if (!opts.files) {
    console.log(nomnom.getUsage());
    process.exit(0);
}

class FileProcessor {
    constructor(debugMode, stdout) {
        this.debugMode = debugMode;
        this.stdout = stdout;
    }

    processFile(fileName) {
        fs.readFile(fileName, "utf-8", (error, contents) => {
            if (error) { return console.log(error); }
            this.processFileContents(contents);
        });
    }

    processFileContents(contents) {
        let js_source = compiler.compile(this.getParser(), contents);
        if (!js_source) { return; }

        js_source = "// Generated by ASToJS v" + json.version + "\n" +
            "(function() {\n" + js_source + "\n}());";

        js_source = beautify.js_beautify(js_source, { indent_size: 4 });

        if (this.stdout) {
            console.log(js_source);
        } else {
            let outFileNameWithoutExtension = fileName.substring(0, fileName.lastIndexOf('.'));
            this.writeFile(outFileNameWithoutExtension + ".js", js_source);
        }
    }

    getParser() {
        if (this.debugMode) {
            let grammar = fs.readFileSync('./src/parser.pegjs', 'utf8');
            let options = { trace: true, allowedStartRules: ['Start', 'StartComments'] };
            return pegjs.buildParser(grammar, options);
        } else {
            return module.require('./src/parser');
        }
    }

    writeFile(fileName, content) {
        fs.writeFile(fileName, content, error => {
            if (error) { return console.log(error); }
        });
    }
}

let fileProcessor = new FileProcessor(opts.debug, opts.stdout);
opts.files.forEach(fileName => fileProcessor.processFile(fileName));
